# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:latest

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip openssh-client
          - mkdir -p ~/.ssh
          - scp -r $BITBUCKET_CLONE_DIR ubuntu@54.157.211.8:/home/ubuntu/emr.mobihealthinternational.com
          - ssh ubuntu@54.157.211.8 "composer install -d /home/ubuntu/emr.mobihealthinternational.com && sudo -S chown -R www-data:www-data /home/ubuntu/emr.mobihealthinternational.com && sudo -S chmod -R 0755 /home/ubuntu/emr.mobihealthinternational.com && sudo -S mv /home/ubuntu/emr.mobihealthinternational.com /var/www"